//
//
//

const languages = [
  {
    id: "zh",
    name: "Mandarin Chinese",
    flag: require("@/assets/flags/zh.png"),
  },
  { id: "es", name: "Spanish", flag: require("@/assets/flags/es.png") },
  { id: "en", name: "English", flag: require("@/assets/flags/en.png") },
  { id: "hi", name: "Hindi", flag: require("@/assets/flags/hi.png") },
  { id: "ar", name: "Arabic", flag: require("@/assets/flags/ar.png") },
  { id: "bn", name: "Bengali", flag: require("@/assets/flags/bn.png") },
  { id: "pt", name: "Portuguese", flag: require("@/assets/flags/pt.png") },
  { id: "ru", name: "Russian", flag: require("@/assets/flags/ru.png") },
  { id: "ja", name: "Japanese", flag: require("@/assets/flags/ja.png") },
  { id: "pa", name: "Punjabi", flag: require("@/assets/flags/pa.png") },
  { id: "de", name: "German", flag: require("@/assets/flags/de.png") },
  { id: "ko", name: "Korean", flag: require("@/assets/flags/ko.png") },
  { id: "fr", name: "French", flag: require("@/assets/flags/fr.png") },
  { id: "te", name: "Telugu", flag: require("@/assets/flags/te.png") },
  { id: "vi", name: "Vietnamese", flag: require("@/assets/flags/vi.png") },
  { id: "mr", name: "Marathi", flag: require("@/assets/flags/mr.png") },
  { id: "ta", name: "Tamil", flag: require("@/assets/flags/ta.png") },
  { id: "ur", name: "Urdu", flag: require("@/assets/flags/ur.png") },
  { id: "tr", name: "Turkish", flag: require("@/assets/flags/tr.png") },
  { id: "it", name: "Italian", flag: require("@/assets/flags/it.png") },
  { id: "th", name: "Thai", flag: require("@/assets/flags/th.png") },
  { id: "pl", name: "Polish", flag: require("@/assets/flags/pl.png") },
  { id: "fa", name: "Persian", flag: require("@/assets/flags/fa.png") },
  { id: "uk", name: "Ukrainian", flag: require("@/assets/flags/uk.png") },
  { id: "ro", name: "Romanian", flag: require("@/assets/flags/ro.png") },
  { id: "hu", name: "Hungarian", flag: require("@/assets/flags/hu.png") },
  { id: "nl", name: "Dutch", flag: require("@/assets/flags/nl.png") },
  { id: "el", name: "Greek", flag: require("@/assets/flags/el.png") },
  { id: "sv", name: "Swedish", flag: require("@/assets/flags/sv.png") },
  { id: "cs", name: "Czech", flag: require("@/assets/flags/cs.png") },
  { id: "da", name: "Danish", flag: require("@/assets/flags/da.png") },
  { id: "no", name: "Norwegian", flag: require("@/assets/flags/no.png") },
  { id: "fi", name: "Finnish", flag: require("@/assets/flags/fi.png") },
  { id: "lt", name: "Lithuanian", flag: require("@/assets/flags/lt.png") },
  { id: "lv", name: "Latvian", flag: require("@/assets/flags/lv.png") },
  { id: "et", name: "Estonian", flag: require("@/assets/flags/et.png") },
  { id: "sk", name: "Slovak", flag: require("@/assets/flags/sk.png") },
  { id: "sl", name: "Slovenian", flag: require("@/assets/flags/sl.png") },
  { id: "bg", name: "Bulgarian", flag: require("@/assets/flags/bg.png") },
  { id: "hr", name: "Croatian", flag: require("@/assets/flags/hr.png") },
  { id: "sr", name: "Serbian", flag: require("@/assets/flags/sr.png") },
  { id: "he", name: "Hebrew", flag: require("@/assets/flags/he.png") },
  { id: "ms", name: "Malay", flag: require("@/assets/flags/ms.png") },
  { id: "kn", name: "Kannada", flag: require("@/assets/flags/kn.png") },
  { id: "ml", name: "Malayalam", flag: require("@/assets/flags/ml.png") },
  { id: "gu", name: "Gujarati", flag: require("@/assets/flags/gu.png") },
  { id: "ne", name: "Nepali", flag: require("@/assets/flags/ne.png") },
  { id: "si", name: "Sinhala", flag: require("@/assets/flags/si.png") },
  { id: "lo", name: "Lao", flag: require("@/assets/flags/lo.png") },
  { id: "km", name: "Khmer", flag: require("@/assets/flags/km.png") },
  { id: "am", name: "Amharic", flag: require("@/assets/flags/am.png") },
  { id: "sw", name: "Swahili", flag: require("@/assets/flags/sw.png") },
  { id: "zu", name: "Zulu", flag: require("@/assets/flags/zu.png") },
  { id: "xh", name: "Xhosa", flag: require("@/assets/flags/xh.png") },
  { id: "yo", name: "Yoruba", flag: require("@/assets/flags/yo.png") },
  { id: "ig", name: "Igbo", flag: require("@/assets/flags/ig.png") },
  { id: "ha", name: "Hausa", flag: require("@/assets/flags/ha.png") },
  { id: "so", name: "Somali", flag: require("@/assets/flags/so.png") },
  { id: "rw", name: "Kinyarwanda", flag: require("@/assets/flags/rw.png") },
  { id: "ny", name: "Chichewa", flag: require("@/assets/flags/ny.png") },
  { id: "sn", name: "Shona", flag: require("@/assets/flags/sn.png") },
  { id: "kg", name: "Kongo", flag: require("@/assets/flags/lg.png") },
  { id: "ln", name: "Lingala", flag: require("@/assets/flags/lg.png") },
  { id: "om", name: "Oromo", flag: require("@/assets/flags/om.png") },
  { id: "sq", name: "Albanian", flag: require("@/assets/flags/sq.png") },
  { id: "is", name: "Icelandic", flag: require("@/assets/flags/is.png") },
  { id: "hy", name: "Armenian", flag: require("@/assets/flags/hy.png") },
  { id: "kk", name: "Kazakh", flag: require("@/assets/flags/kk.png") },
  { id: "uz", name: "Uzbek", flag: require("@/assets/flags/uz.png") },
];

export default languages;
